# Docker Compose Override for Development
# This file extends compose.yaml with development-specific settings
# It's automatically loaded by docker compose when present

services:
  web:
    # Enable debugging and development features
    environment:
      - DEBUG=true
      - NUXT_DEBUG=true
      # NODE_OPTIONS removed to avoid port conflict - uncomment if needed
      # - NODE_OPTIONS=--inspect=0.0.0.0:9229 --openssl-legacy-provider
    ports:
      - "3000:3000"
      # Debugger port removed to avoid conflict - uncomment if needed
      # - "9229:9229"
    # Override development command for debugging
    # Uncomment the line below to enable debugging
    # command: ["node", "--inspect=0.0.0.0:9229", "node_modules/.bin/nuxt", "dev"]
    
    # Development-specific volume mounts
    volumes:
      # Mount source code for hot reload
      - .:/app:cached
      # Exclude node_modules from being overwritten
      - /app/node_modules
      # Exclude .nuxt directory - let container manage it
      - /app/.nuxt
      # Mount specific directories for hot reload
      - ./static:/app/static:cached
      - ./assets:/app/assets:cached
      - ./components:/app/components:cached
      - ./layouts:/app/layouts:cached
      - ./middleware:/app/middleware:cached
      - ./pages:/app/pages:cached
      - ./plugins:/app/plugins:cached
      - ./server:/app/server:cached
      - ./store:/app/store:cached
    
    # Development-specific labels for easier identification
    labels:
      - "dev.shogiwebroom.service=web"
      - "dev.shogiwebroom.environment=development"

  redis:
    # Development-specific Redis configuration
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=everysec
    
    # Development-specific labels
    labels:
      - "dev.shogiwebroom.service=redis"
      - "dev.shogiwebroom.environment=development"
    
    # Enable Redis CLI access for debugging
    command: >
      redis-server 
      --appendonly yes 
      --appendfsync everysec 
      --save 60 1 
      --loglevel notice 
      --maxmemory 256mb 
      --maxmemory-policy allkeys-lru