version: "3.8"

services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - 8080:3000
    working_dir: /src
    volumes:
      - ./src:/src
      - node_modules-volume:/src/node_modules
    environment:
      HOST: 0.0.0.0
      REDIS_URL: redis

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379

volumes:
  node_modules-volume:
  redis-volume:
